### ISSUE TITLE
uninitialized constant AWS

### ISSUE THREAD

**Issue by mrvudo** [ka8725/redmine_s3#29]
I've installed redmine_s3. I've followed the instructions I don't know what 6. Restart mongrel/upload to production/whatever is. I'm assuming it means restart the server.

**Environment:**

```
  Redmine version                2.5.3.stable.13559
  Ruby version                   2.0.0-p594 (2014-10-27) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
```

When I use rake redmine_s3:files_to_s3 or rake redmine:plugins RAILS_ENV=production I get the error below

``` 
rake aborted!
uninitialized constant AWS
/srv/redmine/plugins/redmine_s3/lib/redmine_s3/connection.rb:3:in `<top (required)>'
/srv/redmine/plugins/redmine_s3/lib/redmine_s3.rb:3:in `<top (required)>'
/srv/redmine/plugins/redmine_s3/init.rb:1:in `<top (required)>'
/srv/redmine/lib/redmine/plugin.rb:133:in `block in load'
/srv/redmine/lib/redmine/plugin.rb:124:in `each'
/srv/redmine/lib/redmine/plugin.rb:124:in `load'
/srv/redmine/config/initializers/30-redmine.rb:19:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/srv/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/application.rb:103:in `require_environment!'
/usr/local/rvm/gems/ruby-2.0.0-p594/gems/railties-3.2.19/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/srv/redmine/lib/tasks/redmine.rake:52:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
```

```
production:
  access_key_id: key_id
  secret_access_key: access_key
  bucket: stables-files
  folder:
  endpoint:
  secure: 
  private:
  expires:
  proxy:

development:
  access_key_id:
  secret_access_key:
  bucket:
  folder:
  endpoint:
  secure:
  private:
  expires:
  proxy:

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:



```
