### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by sadfuzzy** [ka8725/redmine_s3#35]
Getting this
```
[AWS S3 403 0.105821 0 retries] get_bucket_versioning(:bucket_name=>"test-redmine") AWS::S3::Errors::AccessDenied Access Denied
``` 
for attachment links in letters,
but I can see/add/edit files in issue card and they work correctly.
Settings:

```yaml
production:
  access_key_id: my_id
  secret_access_key: my_key
  bucket: test-redmine
  folder: attachments
  private: true
  region: eu-west-1
```
